#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""Warm up task week 07"""

def fibonacci(maxint):
    """Integer to be celing.
    Args:
        maxint(int): Top for the while loop.
    Returns:
        A list of sequence of numbers generated by the loop
    Examples:
        >>> fibonacci(10)
        [0, 1, 1, 2, 3, 5, 8]
    """
    int1, int2 = 0, 1
    fiblist = [int1, ]
    while int2 < maxint:
        fiblist.append(int2)
        int1, int2 = int2, int1 + int2
    return fiblist
